const assert=require('node:assert/strict'),fs=require('node:fs');
const {parseFathom,parseLocal,inferredDate,safeURL}=require('../lib/rewind/cinema');
const events=parseFathom(fs.readFileSync(__dirname+'/fixtures/fathom.html','utf8'),'2026-10-05');
assert.ok(events.length);const range=events.find(e=>e.ranges.length);assert.ok(range);assert.equal(range.dates.length,0,'A national date window must not invent daily screenings');assert.equal(range.scope,'national');
const local=parseLocal(fs.readFileSync(__dirname+'/fixtures/kalispell.html','utf8'),'2026-10-05');assert.ok(local.length);assert.ok(local[0].screenings.length);assert.ok(local[0].screenings.every(s=>s.date>='2026-10-05'&&s.time&&s.url.startsWith('https://tickets.fandango.com/')));
assert.equal(inferredDate(1,23,'2026-12-25'),'2027-01-23');assert.equal(inferredDate(12,31,'2027-01-02'),'2026-12-31');assert.equal(inferredDate(2,31,'2026-10-05',2027),null);
assert.throws(()=>parseFathom('<h1>blocked</h1>'));assert.throws(()=>parseLocal('<h1>blocked</h1>'));assert.equal(safeURL('https://evil.com/pay',['tickets.fandango.com']),null);
console.log('Cinema: source fixtures, national windows vs exact screenings, ticket hosts, calendar year rollover and layout failures passed');
const {normalizeLocalService}=require('../lib/rewind/cinema');
const body={generated_at:new Date().toISOString(),movies:[{title:'Favorite',dates:['2026-10-06','2026-10-08','bad']} ]};
const normalized=normalizeLocalService(body,'2026-10-05');assert.equal(normalized[0].dates.length,2);assert.equal(normalized[0].screenings.length,0,'A date-only feed must not invent screening times');assert.throws(()=>normalizeLocalService({error:'down',movies:[]},'2026-10-05'));
(async()=>{const {refreshCinema}=require('../lib/rewind/cinema'),original=global.fetch,calls=[];let direct='ok',backupTime=new Date(Date.now()-3600000).toISOString();
 global.fetch=async url=>{calls.push(url);if(url.includes('onrender'))return {ok:true,json:async()=>({generated_at:backupTime,movies:[{title:'Backup',dates:['2099-10-07']}]})};if(url.includes('tributemovies')){if(direct==='fail')throw Error('Unavailable');return {ok:true,text:async()=>direct==='empty'?'<li class="movie-info-box"><h2 class="media-heading">No future showtimes</h2></li>':fs.readFileSync(__dirname+'/fixtures/kalispell.html','utf8')};}return {ok:true,text:async()=>fs.readFileSync(__dirname+'/fixtures/fathom.html','utf8')};};
 try{await refreshCinema();assert.equal(calls.some(u=>u.includes('onrender')),false,'Direct success must not wait on the sleeping backup');calls.length=0;direct='empty';const empty=await refreshCinema();assert.equal(empty.local.items.length,0);assert.equal(empty.local.stale,false);assert.equal(calls.some(u=>u.includes('onrender')),false,'Verified empty is authoritative');direct='fail';const backup=await refreshCinema();assert.equal(backup.local.checkedAt,Date.parse(backupTime),'Backup freshness is the source timestamp');global.fetch=async()=>{throw Error('outage')};const old={local:{items:[{title:'Expired'}],checkedAt:Date.now()-37*3600000},events:{items:[{title:'Still bounded'}],checkedAt:Date.now()-2*86400000}};const failed=await refreshCinema(old);assert.equal(failed.local.items.length,0);assert.equal(failed.events.items.length,1);assert.equal(failed.events.stale,true);console.log('Cinema refresh: direct precedence, valid empty, real source timestamp and bounded outage retention passed');}finally{global.fetch=original;}
})().catch(e=>{console.error(e);process.exitCode=1});
