[build]
  command = "echo no build step needed yet"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."scheduled-discovery"]
  schedule = "@hourly"

[functions."scheduled-already-released-move"]
  schedule = "@hourly"
